---
- name: Install required packages
  ansible.builtin.apt:
    name: "{{ slurm_setup_package_names }}"
    state: present

- name: Set up slurm head node
  when: inventory_hostname in groups['head_node']
  block:
    - name: Install Slurm Workload manager
      ansible.builtin.apt:
        name: "slurm-wlm={{ slurm_setup_slurm_version }}"
        state: present

    - name: Fecth munge.key to host
      ansible.builtin.fetch:
        src: /etc/munge/munge.key
        dest: ./roles/slurm_setup/files/munge.key
        flat: true
        force: true

- name: Set up slurm compute node
  when: inventory_hostname in groups['compute_node']
  block:
    - name: Install Slurm deamon
      ansible.builtin.apt:
        name: "slurmd={{ slurm_setup_slurm_version }}"
        state: present

    - name: Install Slurm Client
      ansible.builtin.apt:
        name: "slurm-client={{ slurm_setup_slurm_version }}"
        state: present

    - name: Copy munge.key
      ansible.builtin.copy:
        src: munge.key
        dest: /etc/munge/munge.key
        owner: munge
        group: munge
        mode: '0400'

- name: Set up common Slurm configuration
  block:
    - name: Copy slurm.conf to node
      ansible.builtin.template:
        src: slurm.j2
        dest: /etc/slurm/slurm.conf
        owner: slurm
        group: slurm
        mode: '0444'

    - name: Copy cgroup.conf to node
      ansible.builtin.copy:
        src: cgroup.conf
        dest: /etc/slurm/cgroup.conf
        owner: slurm
        group: slurm
        mode: '0400'

    - name: Enable and start munge service
      ansible.builtin.systemd:
        name: munge
        enabled: true
        state: started

    - name: Enable and start slurmd service
      ansible.builtin.systemd:
        name: slurmd
        enabled: true
        state: started

    - name: Enable and start slurmctld service
      ansible.builtin.systemd:
        name: slurmctld
        enabled: true
        state: started
      when: inventory_hostname in groups['head_node']

    - name: Reboot the machine (Wait for 100 seconds)
      ansible.builtin.reboot:
        reboot_timeout: 100
