---
slurm_setup_package_names:
  - ntpdate
  - libpmix-dev

slurm_setup_slurm_version: "22.05.8-4+deb12u2"

slurm_setup_cluster_name: "cluster"
slurm_setup_resource_selection: "cons_res"
slurm_setup_resource_allocate_type: "CR_Core"
slurm_setup_proctrack_type: "cgroup"
slurm_setup_task_plugins: "none"
slurm_setup_jobacctgather_type: "cgroup"

slurm_setup_hosts_mapping:
  head_node:
    - ip: "10.0.10.11"
      hostname: "head-node1"
      CPUs: 4
      Sockets: 1
      CoresPerSocket: 4
      ThreadsPerCore: 1
      RealMemory: 907
  compute_node:
    - ip: "10.0.10.101"
      hostname: "compute-node1"
      CPUs: 4
      Sockets: 1
      CoresPerSocket: 4
      ThreadsPerCore: 1
      RealMemory: 907
